spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/autostop}
    username: ${DB_USERNAME:autostop}
    password: ${DB_PASSWORD:autostop}
  jpa:
    show-sql: false

autostop:
  demo:
    simulator-enabled: true
